AllCops:
  Exclude:
    - "vendor/**/*"
    - "Gemfile"
    - "Guardfile"
    - "slappy.gemspec"
  DisplayCopNames: true
  RunRailsCops: false

##################### Style ##################################

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

##################### Metrics ##################################

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20
